import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Recupera Zap',
  description: 'Generated by create next app',
  keywords: [],
};

import { Providers } from './contexts/providers';

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
